ALTER TABLE DOCTORES
    ADD COLUMN IF NOT EXISTS aviso_expira_en TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS aviso_visible_portal BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS aviso_visible_chatbot BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS aviso_visible_web BOOLEAN NOT NULL DEFAULT TRUE;
